### ISSUE TITLE
Login: fix error message and OAuth

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/react-invenio-app-ils#145]
There are 2 issues in the Login.js component:

- [x] Notifications (success or error) are shown 2 times, probably because the `<Notifications` cmp is added.
- [ ] Notifications are outside the background.
- [x] There should be no notifications in the frontsite, replace them with a box in the login page
- [x] It is not possible to override the OAuth config and removing existing OAuth login (e.g. `GitHub`): probably when merging overridden config, we should use `assign` instead of `merge`? To be checked.

See screenshot:

![login](https://user-images.githubusercontent.com/2089455/89046036-b96b1780-d34c-11ea-9248-b37a18d277ea.png)

**Comment by FlorianCassayre** [comment]
It seems the UI issue is solved; moreover the OAuth component was already made extensible. Will link the PRs when I find them.

**Comment by ntarocco** [comment]
The issue is still present. To reproduce, just go to: http://localhost:3000/login?message=error&code=400
